title : Biomechanika pro bakaláře
author: Matej Daniel
logo: 'biomechanika_pro_bakalare.png'

# Short description about the book
description: >-
  Úvod do biomechaniky pro studenty bakalářského studia na ČVUT v Praze

execute:
  execute_notebooks           : cache

# HTML-specific settings
html:
  home_page_in_navbar         : false

# Interact link settings
notebook_interface            : "notebook"

# Launch button settings
repository:
  url                         : https://github.com/matejdaniel/Biomechanika
  path_to_book                : "Book"

binder:
  binderhub_url               : "https://mybinder.org"
  text                        : "Launch binder"

# LaTeX settings
bibtex_bibfiles:
   - _bibliography/references.bib
latex:
  latex_engine                : "xelatex"
  latex_documents:
    targetname: book.tex
